spring:
  application:
    name: spring-security-jwt
  datasource:
    # url: jdbc:postgresql://localhost:5432/spring-security
    url: jdbc:mysql://127.0.0.1:3306/spring-security
    username: root
    password: C8aJEVCCvSA1VFi8
    # driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    show-sql: true
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    # database: postgresql
    # database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 1001
  error:
    include-message: always

rsa:
  private-key: classpath:certs/private-keyy.pem
  public-key: classpath:certs/public-key.pem

logging:
  level:
    org:
      springframework: INFO